### ISSUE TITLE
Cannot access Nvidia-grafana on Openshift 4.2 because required 'Change Password' on first login for username=admin fails with "unauthorized" 

### ISSUE THREAD

**Issue by dfeddema** [openshift-psap/special-resource-operator-deprecated#15]
Nvidia-grafana is installed by the SRO operator.  On Openshift 4.2 with SRO operator running and Nvidia-grafana installed, users cannot access the nvidia-grafana dashboards.  This is because the first time a user logs into nvidia-grafana  as user "admin"
(username=admin,password=admin) they are required to reset the admin password.  On Openshift 4.2 the password reset fails with message "unauthorized".   Because the admin login fails, no one can login to the nvidia-grafana dashboard and view the GPU metrics.

![Unauthorized_Screenshot](https://user-images.githubusercontent.com/3208719/76133264-3aa3c580-5fcc-11ea-865c-f65c9953e5b0.png)

**Comment by shgriffi** [comment]
For full transparency, we have a number of OEM partners that are scheduled to do joint presentations and sales opportunities with our teams at RH Summit.  This is currently blocking those efforts because we cant complete our publications that are going out prior to Summit, which unfortunately puts an urgency on this for resolution.  Any help would be greatly appreciated.

**Comment by zvonkok** [comment]
@dfeddema @shgriffi This error occurs due to the use of the "Scyld Cloud Workstation" + ssh tunneling. We were able to change the password of Grafana when ssh tunnelling the Grafana instance and not the "Scyld Cloud Workstation". 

Closing this as NOTABUG, its the way how Grafana was accessed (too many redirects?).
